app_transmission:
  name: transmission

  folders:
    - medias/downloads/watch
    - medias/downloads/complete
    - medias/downloads/incomplete

  portal:
    - name: Transmission
      subtitle: "Téléchargement"
      url: "https://transmission.{{ cloudflare_domain }}"
      logo: https://github.com/NX211/homer-icons/raw/master/png/transmission.png
      target: "_blank"
      group: video
      public: false

  namespace: sh-flix

  helm_repo:
    - name: k8s-at-home
      repo_url: https://k8s-at-home.com/charts/

  charts:
    - ref: "k8s-at-home/transmission"
      chart_values:
        env:
          TRANSMISSION_WEB_HOME: /web
          TRANSMISSION_DOWNLOAD_DIR: /downloads/complete
          TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
          TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
          TRANSMISSION_WATCH_DIR_ENABLED: true
          TRANSMISSION_WATCH_DIR: /downloads/watch
        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            hosts:
              - host: "transmission.{{ cloudflare_domain }}"
                paths:
                  - path: "/"
                    pathType: Prefix
          external:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: external
              external-dns.alpha.kubernetes.io/target: "{{ cloudflare_backend }}"
              traefik.ingress.kubernetes.io/router.tls: "true"
              traefik.ingress.kubernetes.io/router.middlewares: sh-core-forward-auth@kubernetescrd,sh-core-cloudflare-api-whitelist@kubernetescrd
            hosts:
              - host: "transmission.{{ cloudflare_domain }}"
                paths:
                  - path: "/"
                    pathType: Prefix
        persistence:
          config:
            enabled: true
            type: hostPath
            mountPath: /config
            hostPath: "/home/kah/config/transmission"

          medias:
            enabled: true
            type: hostPath
            mountPath: /medias
            hostPath: "/home/kah/medias"
