---


apps_without_portal:
  # core
  - "{{ app_traefik }}"
  - "{{ app_adguard }}"
  - "{{ app_monitoring }}"
  - "{{ app_externaldns}}"
  - "{{ app_whoami}}"
  # flix
  - "{{ app_jackett }}"
  - "{{ app_transmission }}"
  - "{{ app_radarr }}"
  - "{{ app_sonarr }}"
  - "{{ app_bazarr }}"
  - "{{ app_jellyfin }}"

apps: "{{ apps_without_portal + [app_portal_public, app_portal_private] }}"


sh_apps_path_base: "/home/kah/"
sh_apps_owner: kah
sh_apps_group: kah
sh_apps_mode: '700'
