---


apps_without_portal:
  # core
  - "{{ app_traefik }}"
  - "{{ app_blocky }}"
  - "{{ app_monitoring }}"
  - "{{ app_externaldns}}"
  - "{{ app_whoami}}"
  - "{{ app_portainer}}"
  - "{{ app_forwardauth }}"
  # flix
  - "{{ app_jackett }}"
  - "{{ app_transmission }}"
  - "{{ app_radarr }}"
  - "{{ app_sonarr }}"
  - "{{ app_bazarr }}"
  - "{{ app_jellyfin }}"
  # data
  - "{{ app_mariadb }}"
  - "{{ app_mosquitto }}"
  - "{{ app_influxdb }}"
  # home
  - "{{ app_esphome }}"
  - "{{ app_hass }}"
  - "{{ app_zigbee2mqtt }}"

apps: "{{ apps_without_portal + [app_portal_public, app_portal_private] }}"


sh_apps_path_base: "/data"
sh_apps_owner: 568
sh_apps_group: 568
sh_apps_mode: '755'

sh_apps_debug: false
