---
cloudflare_api_key: !vault |
                    $ANSIBLE_VAULT;1.1;AES256
                    63336161613464336530343138353738366163313839613033316631613233323964663362656138
                    3462636661366665663330353931373238383562336238380a303135393431383362346663393639
                    39666432376535623232656537353263643964366334363564353230653664633630376563376162
                    6330333562373363640a393631306334643235383536363331386365306338323538656261353133
                    61356438373566633136366638636639386236373239303934366332643064313238353237636232
                    6638646130306131316464323733333762646239383939393133
cloudflare_api_email: !vault |
                      $ANSIBLE_VAULT;1.1;AES256
                      32643639303364323132343935303034623562636631616664313238653139356436633635613533
                      6233383463643137373535626231326130653337363939310a343730313162356631313238633165
                      64373937646361636462653233366164663034343233303135666563333964623737376561323661
                      3935653361393138660a633764363165363461653134363939623835386232626234656664623030
                      32666166306263633530353737326166373562313239333035646662326131366334
cloudflare_domain: !vault |
                   $ANSIBLE_VAULT;1.1;AES256
                   30356339376361393831653336393461353033323134386639373566643362316233356431376439
                   3832636538306239633431636566626466313566363037370a353434636134626165656231656534
                   61383036373032373362306632323163656363366632666635393633663066323931396433343264
                   6334306135383633370a316538623131653933313461303465656533303461353837346130393830
                   3661
cloudflare_backend: !vault |
                    $ANSIBLE_VAULT;1.1;AES256
                    36666661653932323732623030663530353361393839366330633863633332646663386163303565
                    3061616435626232656661333437323061323837666635630a616131383531393363356165326234
                    61656534373334663264383564633639326336303830333037663531313638663732303739363765
                    3934376563303262320a393134646138666637653830333032363136373161393764326165356633
                    6131
cloudflare_ips:
  - "103.21.244.0/22"
  - "103.22.200.0/22"
  - "103.31.4.0/22"
  - "104.16.0.0/13"
  - "104.24.0.0/14"
  - "108.162.192.0/18"
  - "131.0.72.0/22"
  - "141.101.64.0/18"
  - "162.158.0.0/15"
  - "172.64.0.0/13"
  - "173.245.48.0/20"
  - "188.114.96.0/20"
  - "190.93.240.0/20"
  - "197.234.240.0/22"
  - "198.41.128.0/17"
  - "2400:cb00::/32"
  - "2606:4700::/32"
  - "2803:f800::/32"
  - "2405:b500::/32"
  - "2405:8100::/32"
  - "2a06:98c0::/29"
  - "2c0f:f248::/32"
