mariadb_auth_rootPassword: !vault |
                           $ANSIBLE_VAULT;1.1;AES256
                           33663263386164626166633064643162373736633936666566343030366439373064303637623636
                           3265656234623439616339323534353462396132663737330a373031376463663337323261306561
                           37313838326630353265623430616131666337373035306432316336316163383038633833333134
                           3765623631353338380a383634386132653239303164343738663164343730326265323036643636
                           3436
