app_portal_public_configmap:
  title: Sillyhome
  subtitle: Portal
  icon: "fas fa-house-user"
  footer: ''
  columns: "auto"
  links:
    - name: "Github"
      icon: "fab fa-github"
      url: "https://github.com/bpaulin"
      target: "_blank"
    - name: "Website"
      icon: "fas fa-book"
      url: "https://bpaulin.net"
      target: "_blank"
    - name: "Portal"
      icon: "fas fa-sign-in-alt"
      url: "https://portal.{{ cloudflare_domain }}"
  services: "{{ apps_without_portal | apps_for_portal(app_portal_base, true, false) }}"

app_portal_public:
  name: portal-public

  namespace: sh-core

  helm_repo:
    - name: k8s-at-home
      repo_url: https://k8s-at-home.com/charts/

  charts:
    - ref: "k8s-at-home/homer"
      chart_values:
        ingress:
          main:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.entrypoints: external
              traefik.ingress.kubernetes.io/router.middlewares: sh-core-cloudflare-api-whitelist@kubernetescrd
            hosts:
              - host: "{{ cloudflare_domain }}"
                paths:
                  - path: "/"
                    pathType: Prefix
        configmap:
          config:
            enabled: true
            data:
              config.yml: "{{ app_portal_public_configmap | to_json }}"
